version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: wellcoach/well_coach_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media