version: '3.3'

services:
  frontend_nutr:
    container_name: front_ptan_test
    build: ./frontend
    volumes:
      - volumes_front:/app/dist/
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: 'backend'
    build: ./backend/
    env_file: .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media
    depends_on:
      - db
  nginx:
    container_name: 'gateway'
    build: ./gateway/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
      - media_value:/var/html/media
      - volumes_front:/usr/share/nginx/html/front/
    depends_on:
      - backend
      - frontend_nutr

volumes:
  pg_data:
  static_value:
  media_value:
  volumes_front:
