# Generated by Django 4.2.4 on 2024-02-12 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название упражнения', max_length=128, verbose_name='Название упражнения')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите ссылку на картинку к упражнению', null=True, upload_to='exercises', verbose_name='Ссылка на картинку к упражнению')),
                ('describe', models.TextField(blank=True, help_text='Введите описание упражнения', null=True, verbose_name='Описание упражнения')),
                ('target_muscles', models.TextField(blank=True, help_text='Введите целевые мышцы', null=True, verbose_name='Целевые мышцы')),
                ('auxiliary_muscles', models.TextField(blank=True, help_text='Введите вспомогательные мышцы', null=True, verbose_name='Вспомогательные мышцы')),
                ('link', models.CharField(blank=True, help_text='Введите ссылку на видео выполнения упражнения', max_length=300, null=True, verbose_name='Ссылка на видео выполнения упражнения')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания упражнения', verbose_name='Дата создания упражнения')),
                ('edit_dt', models.DateTimeField(auto_now=True, help_text='Введите дату редактирования упражнения', verbose_name='Дата редактирования упражнения')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['-create_dt'],
            },
        ),
        migrations.CreateModel(
            name='ExercisesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, help_text='Введите описание списка упражнений', null=True, verbose_name='Описание списка упражнений')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания списка упражнений', verbose_name='Дата создания списка упражнений')),
                ('edit_dt', models.DateTimeField(auto_now=True, help_text='Введите дату редактирования списка упражнений', verbose_name='Дата редактирования списка упражнений')),
                ('exercise', models.ForeignKey(blank=True, help_text='Введите список упражнений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_list_exercise', to='workouts.exercise', verbose_name='Список упражнений')),
            ],
            options={
                'verbose_name': 'Список упражнений',
                'verbose_name_plural': 'Списки упражнений',
                'ordering': ['-create_dt'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], help_text='Введите номер дня недели от 1 до 7', max_length=50, verbose_name='Номер дня недели')),
                ('training_date', models.DateTimeField(blank=True, help_text='Введите дату тренировки', null=True, verbose_name='Дата тренировки')),
                ('is_done', models.BooleanField(blank=True, help_text='Введите статус выполнения тренировки', null=True, verbose_name='Тренировка выполнена')),
                ('user_comment', models.TextField(blank=True, help_text='Введите комментарий клиента к тренировке', null=True, verbose_name='Комментарий клиента к тренировке')),
                ('spec_comment', models.TextField(blank=True, help_text='Введите комментарий специалиста к тренировке', null=True, verbose_name='Комментарий специалиста к тренировке')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания списка упражнений', null=True, verbose_name='Дата создания списка упражнений')),
                ('edit_dt', models.DateTimeField(auto_now=True, help_text='Введите дату редактирования списка упражнений', null=True, verbose_name='Дата редактирования списка упражнений')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите название плана тренировок', max_length=128, verbose_name='Название плана тренировок')),
                ('describe', models.TextField(blank=True, help_text='Введите описание плана тренировки', max_length=300, verbose_name='Описание плана тренировки')),
                ('start_date', models.DateTimeField(blank=True, help_text='Введите дату начала плана тренировки', null=True, verbose_name='Дата начала плана тренировки')),
                ('end_date', models.DateTimeField(blank=True, help_text='Введите дату окончания плана тренировки', null=True, verbose_name='Дата окончания плана тренировки')),
                ('is_active_user', models.BooleanField(blank=True, null=True, verbose_name='План тренировки не удален клиентом')),
                ('is_active_spec', models.BooleanField(blank=True, null=True, verbose_name='План тренировки не удален специалистом')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания плана тренировки', verbose_name='Дата создания плана тренировки')),
                ('edit_dt', models.DateTimeField(auto_now=True, help_text='Введите дату редактирования плана тренировки', verbose_name='Дата редактирования плана тренировки')),
                ('specialist', models.ForeignKey(help_text='Специалист', on_delete=django.db.models.deletion.CASCADE, related_name='spec_training_plan', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'План тренировки',
                'verbose_name_plural': 'Планы тренировок',
                'ordering': ['-create_dt'],
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название типа тренировки', max_length=128, verbose_name='Название типа тренировки')),
                ('describe', models.TextField(blank=True, help_text='Введите описание типа тренировки', null=True, verbose_name='Описание типа тренировки')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания типа тренировки', verbose_name='Дата создания типа тренировки')),
                ('edit_dt', models.DateTimeField(auto_now=True, help_text='Введите дату редактирования типа тренировки', verbose_name='Дата редактирования типа тренировки')),
            ],
            options={
                'verbose_name': 'Тип тренировки',
                'verbose_name_plural': 'Типы тренировок',
                'ordering': ['-create_dt'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_training_plan', to='workouts.training', verbose_name='Тренировка')),
                ('training_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plan_train', to='workouts.trainingplan', verbose_name='Тренировочный план')),
            ],
            options={
                'verbose_name': 'Связь тренировки cо списком упражнений',
                'verbose_name_plural': 'Связи тренировок cо списками упражнений',
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='training',
            field=models.ManyToManyField(blank=True, help_text='Тренировочный план', related_name='training_training_plan', through='workouts.TrainingPlanTraining', to='workouts.training', verbose_name='Тренировочный план'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='user_training_plan', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='TrainingExercisesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_exercises_list', to='workouts.exerciseslist', verbose_name='Список упражнений')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_exercises_list', to='workouts.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Связь тренировки cо списком упражнений',
                'verbose_name_plural': 'Связи тренировок cо списками упражнений',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='exercises_list',
            field=models.ManyToManyField(blank=True, help_text='Введите списки упражнений в тренировке', related_name='exercises_list_training', through='workouts.TrainingExercisesList', to='workouts.exerciseslist', verbose_name='Списки упражнений в тренировке'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(blank=True, help_text='Введите тип тренировки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_type_training', to='workouts.trainingtype', verbose_name='Тип тренировки'),
        ),
        migrations.AddConstraint(
            model_name='trainingexerciseslist',
            constraint=models.UniqueConstraint(fields=('training', 'exercises_list'), name='unique_training_exercises_list'),
        ),
    ]
