# Generated by Django 4.2.4 on 2023-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату редактирования упражнения', verbose_name='Дата редактирования упражнения'),
        ),
        migrations.AlterField(
            model_name='exerciseslist',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату редактирования списка упражнений', verbose_name='Дата редактирования списка упражнений'),
        ),
        migrations.AlterField(
            model_name='training',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату редактирования списка упражнений', verbose_name='Дата редактирования списка упражнений'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату редактирования плана тренировки', verbose_name='Дата редактирования плана тренировки'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='edit_dt',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату редактирования типа тренировки', verbose_name='Дата редактирования типа тренировки'),
        ),
    ]
