# Generated by Django 4.2.4 on 2023-10-26 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(9),
                    django.core.validators.RegexValidator(
                        message="Допускаются цифры, (), +- и пробел",
                        regex="^[-\\d\\+\\)\\( ]+\\Z",
                    ),
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
