# Generated by Django 4.2.4 on 2023-10-31 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_params_options"),
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = []
